import fs from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import type { Manifest } from "./buildManifest.js";

const require = createRequire(import.meta.url);

/**
 * Writes a static ESM manifest module into the react-static-images package.
 * This file is imported directly by the ImageStatic component.
 */
export async function writeLibraryManifestModule(manifest: Manifest) {
  try {
    // Resolve the installed react-static-images package root
    const pkgRoot = path.dirname(require.resolve("@vividwebau/react-static-images/package.json"));
    const modulePath = path.join(pkgRoot, "static-image-map.js");

    // Write valid ESM module
    const moduleContents =
      "// AUTO-GENERATED BY static-image-pipeline — DO NOT EDIT\n" +
      "export default " +
      JSON.stringify(manifest, null, 2) +
      ";\n";

    await fs.writeFile(modulePath, moduleContents, "utf8");

    console.log(`[Pipeline] Wrote library manifest module: ${modulePath}`);
  } catch (err) {
    console.error("[Pipeline] Failed to write library manifest module:", err);
    throw err;
  }
}
