import Link from 'next/link';
import { ImageStatic } from '@vividweb/react-static-images';
import path from 'path';
import { readFileSync } from 'fs';

// Load manifest from public folder
const manifestPath = path.join(process.cwd(), 'public/static-images.json');
const manifestData = JSON.parse(readFileSync(manifestPath, 'utf-8'));

export default function ResponsiveDemo() {
  const image = manifestData.images[0];

  return (
    <main style={{ padding: '2rem', maxWidth: '1200px', margin: '0 auto' }}>
      <Link href="/" style={{ textDecoration: 'underline' }}>
        ← Back to Home
      </Link>
      <h1>Responsive Images Demo</h1>
      <p>Responsive image sizing with srcset.</p>
      <p>
        Serves appropriately-sized images to different devices, reducing bandwidth
        and improving page load times.
      </p>
      <section>
        <h2>How it works:</h2>
        <ol>
          <li>Pipeline generates multiple size variants of each image</li>
          <li>Create srcset with breakpoints (640w, 1024w, 1920w, etc.)</li>
          <li>Browser selects best size for device/viewport</li>
          <li>Reduces file size for mobile devices</li>
        </ol>
      </section>
      <section>
        <h2>Responsive Image Examples:</h2>
        {image && (
          <div style={{ marginTop: '1rem' }}>
            <p style={{ fontSize: '0.875rem', color: '#666', marginBottom: '0.5rem' }}>
              Available variants: {image.variants?.map((v: any) => `${v.width}w`).join(', ')}
            </p>
            <ImageStatic
              src={image.src}
              alt={image.id}
              width={image.width}
              height={image.height}
              blurDataURL={image.blurDataURL}
              dominantColor={image.dominantColor}
              variants={image.variants}
            />
            <p style={{ marginTop: '0.5rem', fontSize: '0.875rem', color: '#666' }}>
              This image has responsive variants generated by the pipeline
            </p>
          </div>
        )}
      </section>
    </main>
  );
}
